### ISSUE TITLE
Ergebnisse "bonus" werden nicht ausgegeben

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp-freescan#2]
`siwecos/webapp` ist nicht betroffen.

Anscheinend werden nicht alle Testergebnisse eines Scanners angezeigt.

Siehe `staging` Umgebung, beim Header Scanner gibt es die `Referrer-Policy` mit `scoreTypeRaw: bonus`, welche nicht dargestellt wird.

```
{"3":{"name":"Überprüfung der Referrer Policy","hasError":false,"errorMessage":null,"score":0,"testDetails":[{"report":"Die Anweisung 'DIRECTIVE' ist gesetzt.","name":"Die Anweisung 'DIRECTIVE' ist gesetzt."}],"link":"https://siwecos.de/wiki/Referrer-Policy/DE","description":"Referrer Policy unsicher","report":"<p>Eine gut gesetzte Referrer Policy <b>schützt die Privatsphäre</b> Ihrer Webseiten-Besucher, hat aber keinen <i>direkten</i> Einfluss auf die Sicherheit Ihrer Webseite. </p>","scoreTypeRaw":"bonus"}}
```

**Comment by Lednerb** [comment]
webapp ist doch betroffen. Wert `bonus` wird nicht ausgeben.

Einzig `hidden` soll versteckt bleiben.

**Comment by SniperSister** [comment]
Er wird nicht ausgegeben weil er den Score 0 hat - Bonus Scans zeigen wir nur an, wenn sie erfolgreich sind
