### ISSUE TITLE
Anzeige deaktivierte Scanner

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp-freescan#3]
Die Scanner `PORT` und `VERSION` sind im Freescan nicht mehr enthalten.

Um dem Nutzer anzuzeigen, dass nach der Anmeldung weitere Scanner in SIWECOS enthalten sind, sollten die beiden Scanner ausgegraut (hard-coded) unter den Ergebnissen des Freescans angezeigt werden.

**Comment by Lednerb** [comment]
![Bildschirmfoto von 2019-09-14 11-15-10](https://user-images.githubusercontent.com/2056876/64906034-1df39880-d6e1-11e9-986e-2834e4d5c984.png)

Bitte folgende Änderungen durchführen, dann in staging deployen und PR für production öffnen:

1. Zeilenumbruch vor "bitte melden Sie sich an." einfügen
2. Umbenennung: CMS-Versions-Scanner zu `Version Scanner`
3. Umbenennung: Port-Scanner zu `Port Scanner`

Dankeschön.

**Comment by SniperSister** [comment]
Done!

**Comment by Lednerb** [comment]
Bitte nochmal https://github.com/SIWECOS/webapp-freescan/issues/3#issuecomment-531464335 checken

**Comment by SniperSister** [comment]
Zielumbruch und Umbenennungen sind drin, deploy auf Master ist durch - was soll ich da noch checken?

**Comment by Lednerb** [comment]
Sorry mein Fehler, habe lediglich den Commit ed03528 hier in der timeline gesehen.

Danke
